repos:
  - repo: local
    hooks:
      - id: generate_requirements
        name: generate_requirements
        entry: make generate
        language: system
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # find out the latest version -> https://github.com/pre-commit/pre-commit-hooks/releases
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: detect-private-key
  - repo: https://github.com/python-poetry/poetry
    rev: 1.5.1
    hooks:
      - id: poetry-check
  - repo: https://github.com/ambv/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.11
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.3.4"
    hooks:
      - id: ruff
  - repo: https://github.com/pre-commit/mirrors-mypy
    # NOTE: This passes ALL files to `mypy`. mypy will cache these.
    # However, we must ignore all missing imports, because pre-commit runs in a separate env
    rev: "v1.8.0"
    hooks:
      - id: mypy
        pass_filenames: false
        args:
          [
            --config-file,
            pyproject.toml,
            --ignore-missing-imports,
            --install-types,
            --non-interactive,
          ]
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.25.0 # Update to latest version by running `pre-commit autoupdate`
    hooks:
      - id: ggshield
        language: python
        stages: [commit]
        args: ['secret', 'scan', 'pre-commit']
